In [10]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [11]:
#loading the dataset
df = pd.read_csv('Titanic-Dataset.csv')

In [12]:
#first 5 rows of the dataset
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
#last 5 rows of the dataset
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [14]:
#shape of the dataset
df.shape

(891, 12)

In [15]:
#some information of the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [16]:
#printing null values of each features
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [17]:
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

# ***Data Preprocessing***

As the cabin column has 687 missing values out of total 891 values, it is better to drop the column or feature

In [18]:
df = df.drop(columns='Cabin')

In [19]:
#first 5 rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [20]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

The Age column has 177 missing values, but the dataset has total 891 rows, so we cannot drop those rows. Again, age feature could be an important feature for the dataset, so it cannot be dropped. So, we can fill the missing values with mean

In [21]:
df['Age'].mean()

np.float64(29.69911764705882)

In [22]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [23]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

Now the Embarked column has two missing values, which we are going to fill by the mode

In [24]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [25]:
df['Embarked'].mode()[0]

'S'

In [26]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])#mode() returns a series, so [0] should be included

In [27]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

Encoding the categorical data

In [28]:
df = df.replace({'Sex': {'male':0, 'female':1}, 'Embarked': {'S':0,'C':1,'Q':2}})

In [29]:
#df = df.replace({'Sex': {'male':0,'female':1},'Embarked':{'S':0,'C':1,'Q':2}})

In [30]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,1
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,0

# ***Splitting the dataset into features and target***

In [31]:
X = df.drop(columns=['PassengerId','Name','Ticket','Survived'])
y = df['Survived']

# ***Model Selection and hyperparameter tuning using GridSearchCV***

In [32]:
models_list = [LogisticRegression(max_iter=10000),SVC(), KNeighborsClassifier(),RandomForestClassifier()]

In [33]:
hyperparameters = {
    
    'log_reg_parameters':{
        'C':[0.1,0.5,1,5,10,20],
        'solver': ['lbfgs', 'liblinear']
    },
    
    'svm_parameters':{
        'C': [0.1,0.5,1,5,10,20,100],
        'kernel': ['linear','poly','rbf','sigmoid'],
        'gamma': ['scale', 0.1, 0.01, 0.001]
    },
    
    'knn_parameters':{
        'n_neighbors': [3,5,7,9],
        'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
        'weights': ['uniform', 'distance'],
        'metric': ['euclidean', 'manhattan']
    },
    
    'random_forest_parameters': {
        'n_estimators': [20,50,80,100,150,200],
        'criterion': ['gini','entropy','log_loss'],
        'max_depth': [3,4,5,6],
        'max_features': ['sqrt'],
        'min_samples_split':[5,10,15],
        'min_samples_leaf':[2,3,4,5,6],
    }
    
}

In [34]:
hyperparameters.keys()

dict_keys(['log_reg_parameters', 'svm_parameters', 'knn_parameters', 'random_forest_parameters'])

In [35]:
hyperparameters.values()

dict_values([{'C': [0.1, 0.5, 1, 5, 10, 20], 'solver': ['lbfgs', 'liblinear']}, {'C': [0.1, 0.5, 1, 5, 10, 20, 100], 'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'gamma': ['scale', 0.1, 0.01, 0.001]}, {'n_neighbors': [3, 5, 7, 9], 'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'], 'weights': ['uniform', 'distance'], 'metric': ['euclidean', 'manhattan']}, {'n_estimators': [20, 50, 80, 100, 150, 200], 'criterion': ['gini', 'entropy', 'log_loss'], 'max_depth': [3, 4, 5, 6], 'max_features': ['sqrt'], 'min_samples_split': [5, 10, 15], 'min_samples_leaf': [2, 3, 4, 5, 6]}])

In [36]:
hyperparameters['knn_parameters']

{'n_neighbors': [3, 5, 7, 9],
 'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
 'weights': ['uniform', 'distance'],
 'metric': ['euclidean', 'manhattan']}

In [37]:
model_keys = list(hyperparameters.keys())

In [38]:
print(model_keys)

['log_reg_parameters', 'svm_parameters', 'knn_parameters', 'random_forest_parameters']

In [39]:
model_keys[0]

'log_reg_parameters'

In [40]:
def compare_models(list_of_models, dictionary_of_hyperparameters):
    
    results = []
    
    i = 0

    for model in list_of_models:
        
        key = model_keys[i]
        params = dictionary_of_hyperparameters[key]
        
        print(key)
        print(params)
        print('---------------------------------------------------')
        i = i+1
        
        classifier = GridSearchCV(model, params, cv=5)
        
        classifier.fit(X,y)
        
        results.append({
            'model_name': key,
            'best_score': classifier.best_score_,
            'best_hyperparameters': classifier.best_params_
        })
    
    pd.set_option('display.max_colwidth', None)  
    #results_df.iloc[-1]
    results_df = pd.DataFrame(results, columns=['model_name','best_score','best_hyperparameters'])
    return results_df

In [ ]:
compare_models(models_list, hyperparameters)

log_reg_parameters
{'C': [0.1, 0.5, 1, 5, 10, 20], 'solver': ['lbfgs', 'liblinear']}
---------------------------------------------------
svm_parameters
{'C': [0.1, 0.5, 1, 5, 10, 20, 100], 'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'gamma': ['scale', 0.1, 0.01, 0.001]}
---------------------------------------------------

# The best score is found for RandomForestClassifier and best hyperparameters are criterion: 'entropy' and n_estimators: 100

In [ ]:
#Splitting the dataset
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, stratify=y, random_state=2)

In [ ]:
#loading the model
model = RandomForestClassifier(criterion= 'entropy', max_depth= 3, max_features= 'sqrt', min_samples_leaf= 5, min_samples_split= 10, n_estimators= 50, random_state=2)

In [ ]:
#fitting the model
model.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=3, min_samples_leaf=5,
                       min_samples_split=10, n_estimators=50, random_state=2)

# ***Model Evaluation***

In [ ]:
training_prediction = model.predict(X_train)
training_accuracy = metrics.accuracy_score(y_train, training_prediction)
print(f'Accuracy for training data: {training_accuracy}')

Accuracy for training data: 0.8230337078651685

In [ ]:
testing_prediction = model.predict(X_test)
testing_accuracy = metrics.accuracy_score(y_test, testing_prediction)
print(f'Accuracy for the test data: {testing_accuracy}')

Accuracy for the test data: 0.8044692737430168

Use parallel processing

Add:

n_jobs=-1

inside GridSearchCV.

classifier = GridSearchCV(
    model,
    params,
    cv=5,
    n_jobs=-1
)

This uses all CPU cores.

Reduce parameter space
Better Random Forest grid
'random_forest_parameters': {
    'n_estimators': [50,100],
    'criterion': ['gini','entropy'],
    'max_depth': [4,6],
    'min_samples_split':[5,10],
    'min_samples_leaf':[2,4]
}

Only:

2 * 2 * 2 * 2 * 2 = 32 combos

instead of 1080.

Better SVM grid
'svm_parameters':{
    'C': [0.1,1,10],
    'kernel': ['linear','rbf'],
    'gamma': ['scale',0.01]
}

Only:

3 * 2 * 2 = 12 combos

instead of 112.

Use RandomizedSearchCV instead

Much faster.

Example:

from sklearn.model_selection import RandomizedSearchCV

classifier = RandomizedSearchCV(
    model,
    params,
    cv=5,
    n_iter=20,
    n_jobs=-1,
    random_state=2
)

This tests only 20 random combinations.

Another issue

You are fitting on:

classifier.fit(X,y)

instead of train data.

Use:

classifier.fit(X_train, y_train)

Otherwise:

slower
data leakage
unrealistic scores
Recommended practical setup

For Titanic:

cv=3
n_jobs=-1
smaller grids
RandomizedSearchCV for RandomForest and SVM

That usually finishes in minutes instead of hours.